name: publish-to-docker-hub
on: [push]
env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}
  IMAGE_NAME: 'laravel-dev-image'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
      - run: ls -la
      - run: docker build . --file Dockerfile -t ${IMAGE_NAME}
      - run: VERSION="prod-0.1.${GITHUB_JOB}"
      - run: IMAGE=${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}
      - run: docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
      - run: docker push "${IMAGE}:${VERSION}"
