name: publish-to-docker-hub
on:
  schedule:
    - cron: '30 5,17 * * *'
  push:
    branches:
      - main

env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}

jobs:
  publish_on_push_php_7.4:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.push == 'true' }}
    env:
      LANGUAGE_VERSION: 7.4
      LANGUAGE: php
      SEPARATOR: '-'
      IMAGE_NAME: 'laravel-dev-image'
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
      - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
      - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
      - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}${SEPARATOR}${VERSION}"
  publish_on_scheduled_php_7.4:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.schedule == 'true' }}
    env:
      LANGUAGE_VERSION: 7.4
      LANGUAGE: php
      SEPARATOR: '-'
      IMAGE_NAME: 'laravel-dev-image'
      VERSION: 'latest'
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
      - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
      - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
      - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}${SEPARATOR}${VERSION}"
  publish_on_push_python_3.10:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.push == 'true' }}
    env:
      LANGUAGE_VERSION: 3.10
      LANGUAGE: python
      SEPARATOR: '-'
      IMAGE_NAME: 'python-dev'
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
      - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
      - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
      - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}${SEPARATOR}${VERSION}"
  publish_on_scheduled_python_3.10:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.schedule == 'true' }}
    env:
      LANGUAGE_VERSION: 3.10
      LANGUAGE: python
      SEPARATOR: '-'
      IMAGE_NAME: 'python-dev'
      VERSION: 'latest'
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
      - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
      - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
      - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}${SEPARATOR}${VERSION}"
