name: publish-to-docker-hub
on:
  schedule:
    - cron: '30 5,17 * * *'
  push:
    branches:
      - main

env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}

.push_to_docker_hub: &push_to_docker_hub
  steps:
    - uses: actions/checkout@v2
    - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
    - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
    - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
    - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}${SEPARATOR}${VERSION}"

.php_shared_vars: &php_shared_vars
  LANGUAGE_VERSION: 7.4
  LANGUAGE: php
  SEPARATOR: '-'
  IMAGE_NAME: 'laravel-dev-image'

.python_shared_vars: &python_shared_vars
  LANGUAGE_VERSION: 3.10
  LANGUAGE: python
  SEPARATOR: '-'
  IMAGE_NAME: 'python-dev'

jobs:
  publish_on_push_php_7.4_to_docker_hub:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.push == 'true' }}
    env:
      <<: *php_shared_vars
      VERSION: ${{ github.sha }}
    <<: *push_to_docker_hub
  publish_on_scheduled_php_7.4_to_docker_hub:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.schedule == 'true' }}
    env:
      <<: *php_shared_vars
      VERSION: 'latest'
    <<: *push_to_docker_hub
  publish_on_push_python_3.10_to_docker_hub:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.push == 'true' }}
    env:
      <<: *python_shared_vars
      VERSION: ${{ github.sha }}
    <<: *push_to_docker_hub
  publish_on_scheduled_python_3.10_to_docker_hub:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.schedule == 'true' }}
    env:
      <<: *python_shared_vars
      VERSION: 'latest'
    <<: *push_to_docker_hub
